### ISSUE TITLE
grind: hadoop trunk requires Java 8

### ISSUE THREAD

**Issue by jzhuge** [cloudera/dist_test#30]
Every single test failed:

> 2016-10-14 21:13:32 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-cli) on project hadoop-common: Execution default-cli of goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test failed: java.lang.UnsupportedClassVersionError: org/apache/hadoop/test/TimedOutTestsListener : Unsupported major.minor version 52.0 -> [Help 1]

**Comment by umbrant** [comment]
Yea, it sounds like we need to add proper Java multi-version support to the dist_test slaves.

@toddlipcon any thoughts here? We could use the Cloudera toolchain, or just something basic like providing JAVA7_HOME and JAVA8_HOME for users to choose from.

**Comment by jzhuge** [comment]
Here is the test link: http://dist-test.cloudera.org/job?job_id=hadoop.jzhuge.1476479347.17765#

**Comment by toddlipcon** [comment]
We can't really use the Cloudera toolchain because the slaves are outside of the Cloudera network and pretty sure it's not publicly accessible. I think Ubuntu allows multiple Java packages to be installed.

Here's the docker file that we currently use: https://gist.github.com/a574e990e650a34a6ceb00d7cf9cd07d
Feel free to suggest a change

**Comment by jzhuge** [comment]
Sadly there is still no OpenJDK 8 on Ubuntu 14.04, I just voted for [the backport](https://bugs.launchpad.net/trusty-backports/+bug/1368094). We could upgrade Ubuntu to 16.04 or use Oracle Java 8.

**Comment by jzhuge** [comment]
@toddlipcon Where do i get the directory "swarming.client"? https://chromium.googlesource.com/external/swarming.client/?

> ADD swarming.client/ swarming.client/

**Comment by jzhuge** [comment]
Updated Dockerfile ready in https://github.com/jzhuge/dist_test_slave. Haven't tested it yet.

**Comment by jzhuge** [comment]
Might as well include JDK 9.

**Comment by jzhuge** [comment]
ppa:openjdk-r/ppa is maintained by Matthias Klose. It seems pretty trustworthy.

**Comment by jzhuge** [comment]
The grind fix is tracked in https://github.com/cloudera/dist_test/pull/31.

**Comment by jzhuge** [comment]
Docker image built by https://github.com/jzhuge/dist_test_slave works fine.
