### ISSUE TITLE
grind failed to merge test results due to encode error

### ISSUE THREAD

**Issue by jzhuge** [cloudera/dist_test#39]
13:38:51  473.6s	 1839/1840 tests complete
13:42:59  721.0s	 1839/1840 tests complete (1 retries)
13:43:53  775.3s	 1840/1840 tests complete (1 retries)
13:43:55 INFO:dist_test.client:Fetching 1410 artifacts into grind-test-results
13:45:28 INFO:dist_test.client:Extracting 1410 artifacts into grind-test-results
13:45:43 Traceback (most recent call last):
13:45:43   File "/data0/jenkins/workspace/hadoop-gerrit/repos/hadoop/cloudera/supertest/grind/bin/grind", line 592, in <module>
13:45:43     main()
13:45:43   File "/data0/jenkins/workspace/hadoop-gerrit/repos/hadoop/cloudera/supertest/grind/bin/grind", line 569, in main
13:45:43     subcommands[args.subparser_name](config, args)
13:45:43   File "/data0/jenkins/workspace/hadoop-gerrit/repos/hadoop/cloudera/supertest/grind/bin/grind", line 583, in test_subcommand
13:45:43     runner.run()
13:45:43   File "/data0/jenkins/workspace/hadoop-gerrit/repos/hadoop/cloudera/supertest/grind/bin/grind", line 380, in run
13:45:43     self.run_tests()
13:45:43   File "/data0/jenkins/workspace/hadoop-gerrit/repos/hadoop/cloudera/supertest/grind/bin/grind", line 459, in run_tests
13:45:43     merge_xunit.merge_xunit(in_files, "test_results.xml", ignore_flaky=True, quiet=True)
13:45:43   File "/data0/jenkins/workspace/hadoop-gerrit/repos/hadoop/cloudera/supertest/grind/bin/../python/disttest/merge_xunit.py", line 153, in merge_xunit
13:45:43     merge_xml.writexml(open(out_file, 'w'), indent="\t", newl="\n")
13:45:43   File "/usr/lib64/python2.6/xml/dom/minidom.py", line 1749, in writexml
13:45:43     node.writexml(writer, indent, addindent, newl)
13:45:43   File "/usr/lib64/python2.6/xml/dom/minidom.py", line 817, in writexml
13:45:43     node.writexml(writer,indent+addindent,addindent,newl)
13:45:43   File "/usr/lib64/python2.6/xml/dom/minidom.py", line 812, in writexml
13:45:43     _write_data(writer, attrs[a_name].value)
13:45:43   File "/usr/lib64/python2.6/xml/dom/minidom.py", line 303, in _write_data
13:45:43     writer.write(data)
13:45:43 UnicodeEncodeError: 'ascii' codec can't encode character u'\u03bc' in position 40: ordinal not in range(128)
13:45:44 Build step 'Execute shell' marked build as failure

**Comment by jojochuang** [comment]
I filed a pull request to fix this problem: https://github.com/cloudera/dist_test/pull/40

**Comment by jzhuge** [comment]
Fixed by #40
