### ISSUE TITLE
Only test cases from modules with generated test artifact run

### ISSUE THREAD

**Issue by kingamarton** [cloudera/dist_test#56]
There is a check related the existance of the test artifacts the isolate.py file. If there is no such artifact, no isolate files are generated: https://github.com/cloudera/dist_test/blob/master/grind/python/disttest/isolate.py#L155

By default no test artifacts are generated, this *test.jar files are generated by using the maven-jar-plugin. This plugin is missing from a couple of places. I think we should remove this check.

**Comment by toddlipcon** [comment]
ping @umbrant @xiao-chen (I don't know much about the grind side of things)
